# Task1_1=> Write a function to compute 5/0 and use try/except to catch the exceptions.

In [6]:
def div(n,d):
    try:
        a = n/d
    except:
        print("Error 001: Denominator can not be zero, Please correct the input")
    finally:
        print("This is just to practise in this example. Thank you")

div(5,0)

Error 001: Denominator can not be zero, Please correct the input
This is just to practise in this example. Thank you


# Task1_2=> Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [11]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+" "+j+" "+k+".")

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task2_1=>Write a function so that the columns of the output matrix are powers of the input vector.

In [18]:
# Docstring: Generate a Vandermonde matrix.
# np.vander(x, N=None, increasing=False)
import numpy as np

def user_define_vander(inputArr, col, increasing=False):
    if increasing == True:
        op = np.array([x**i for x in inputArr for i in range(col)]).reshape(inputArr.size,col)
    else:
        op = np.array([x**(col-1-i) for x in inputArr for i in range(col)]).reshape(inputArr.size,col)
    
    return op
    
inputArr = np.array([1,2,3])
col = 3

print('1. increasing is True')
print(user_define_vander(inputArr, col, True))

print('\n2. increasing is False')
print(user_define_vander(inputArr, col, False))


1. increasing is True
[[1 1 1]
 [1 2 4]
 [1 3 9]]

2. increasing is False
[[1 1 1]
 [4 2 1]
 [9 3 1]]
